version: '3'
services:
  nginx:
    image: nginx:1.11
    volumes:
      - ../custom-nginx:/usr/share/nginx/html:ro
  curl:
    build: ../curl
    entrypoint:
      - bash
      - -c
      - |-
        while : ; do
          curl -s http://nginx/hello.html;
          sleep 1;
        done
